### ISSUE TITLE
it keeps crashing after the second image and as it's rendering just looks like a corner zoom

### ISSUE THREAD

**Issue by GreyEnt** [beltoforion/ai_ever_zoom#2]
AI Outpainting Zoom Video Generator
-----------------------------------
 - input folder: "/Users/duncanthomson/zoom test 1"
 - output: "video.mp4"
 - fps: 60.0
 - zoom factor: 2.0
 - zoom steps: 100
 - zoom crop: 0.8
 - auto sort: False
 - debug aides: False
 - delay: 0.0
 - reverse: False

Reading images from "/Users/duncanthomson/zoom test 1"
 - 11 images read

Generating Zoom Sequence
 - frame misalignment: zoom_step=0; x_total=-217.00; y_total=16.00; x_step=-217. - frame misalignment: zoom_step=1; x_total=-217.00; y_total=16.00; x_step=-214. - frame misalignment: zoom_step=2; x_total=-217.00; y_total=16.00; x_step=-212. - frame misalignment: zoom_step=3; x_total=-217.00; y_total=16.00; x_step=-210. - frame misalignment: zoom_step=4; x_total=-217.00; y_total=16.00; x_step=-208. - frame misalignment: zoom_step=5; x_total=-217.00; y_total=16.00; x_step=-206. - frame misalignment: zoom_step=6; x_total=-217.00; y_total=16.00; x_step=-203. - frame misalignment: zoom_step=7; x_total=-217.00; y_total=16.00; x_step=-201. - frame misalignment: zoom_step=8; x_total=-217.00; y_total=16.00; x_step=-199. - frame misalignment: zoom_step=9; x_total=-217.00; y_total=16.00; x_step=-197. - frame misalignment: zoom_step=10; x_total=-217.00; y_total=16.00; x_step=-195 - frame misalignment: zoom_step=11; x_total=-217.00; y_total=16.00; x_step=-193 - frame misalignment: zoom_step=12; x_total=-217.00; y_total=16.00; x_step=-190 - frame misalignment: zoom_step=13; x_total=-217.00; y_total=16.00; x_step=-188 - frame misalignment: zoom_step=14; x_total=-217.00; y_total=16.00; x_step=-186 - frame misalignment: zoom_step=15; x_total=-217.00; y_total=16.00; x_step=-184 - frame misalignment: zoom_step=16; x_total=-217.00; y_total=16.00; x_step=-182 - frame misalignment: zoom_step=17; x_total=-217.00; y_total=16.00; x_step=-180 - frame misalignment: zoom_step=18; x_total=-217.00; y_total=16.00; x_step=-177 - frame misalignment: zoom_step=19; x_total=-217.00; y_total=16.00; x_step=-175 - frame misalignment: zoom_step=20; x_total=-217.00; y_total=16.00; x_step=-173 - frame misalignment: zoom_step=21; x_total=-217.00; y_total=16.00; x_step=-171 - frame misalignment: zoom_step=22; x_total=-217.00; y_total=16.00; x_step=-169 - frame misalignment: zoom_step=23; x_total=-217.00; y_total=16.00; x_step=-167 - frame misalignment: zoom_step=24; x_total=-217.00; y_total=16.00; x_step=-164 - frame misalignment: zoom_step=25; x_total=-217.00; y_total=16.00; x_step=-162 - frame misalignment: zoom_step=26; x_total=-217.00; y_total=16.00; x_step=-160 - frame misalignment: zoom_step=27; x_total=-217.00; y_total=16.00; x_step=-158 - frame misalignment: zoom_step=28; x_total=-217.00; y_total=16.00; x_step=-156 - frame misalignment: zoom_step=29; x_total=-217.00; y_total=16.00; x_step=-154 - frame misalignment: zoom_step=30; x_total=-217.00; y_total=16.00; x_step=-151 - frame misalignment: zoom_step=31; x_total=-217.00; y_total=16.00; x_step=-149 - frame misalignment: zoom_step=32; x_total=-217.00; y_total=16.00; x_step=-147 - frame misalignment: zoom_step=33; x_total=-217.00; y_total=16.00; x_step=-145 - frame misalignment: zoom_step=34; x_total=-217.00; y_total=16.00; x_step=-143 - frame misalignment: zoom_step=35; x_total=-217.00; y_total=16.00; x_step=-141 - frame misalignment: zoom_step=36; x_total=-217.00; y_total=16.00; x_step=-138 - frame misalignment: zoom_step=37; x_total=-217.00; y_total=16.00; x_step=-136 - frame misalignment: zoom_step=38; x_total=-217.00; y_total=16.00; x_step=-134 - frame misalignment: zoom_step=39; x_total=-217.00; y_total=16.00; x_step=-132 - frame misalignment: zoom_step=40; x_total=-217.00; y_total=16.00; x_step=-130 - frame misalignment: zoom_step=41; x_total=-217.00; y_total=16.00; x_step=-128 - frame misalignment: zoom_step=42; x_total=-217.00; y_total=16.00; x_step=-125 - frame misalignment: zoom_step=43; x_total=-217.00; y_total=16.00; x_step=-123 - frame misalignment: zoom_step=44; x_total=-217.00; y_total=16.00; x_step=-121 - frame misalignment: zoom_step=45; x_total=-217.00; y_total=16.00; x_step=-119 - frame misalignment: zoom_step=46; x_total=-217.00; y_total=16.00; x_step=-117 - frame misalignment: zoom_step=47; x_total=-217.00; y_total=16.00; x_step=-115 - frame misalignment: zoom_step=48; x_total=-217.00; y_total=16.00; x_step=-112 - frame misalignment: zoom_step=49; x_total=-217.00; y_total=16.00; x_step=-110 - frame misalignment: zoom_step=50; x_total=-217.00; y_total=16.00; x_step=-108 - frame misalignment: zoom_step=51; x_total=-217.00; y_total=16.00; x_step=-106 - frame misalignment: zoom_step=52; x_total=-217.00; y_total=16.00; x_step=-104 - frame misalignment: zoom_step=53; x_total=-217.00; y_total=16.00; x_step=-101 - frame misalignment: zoom_step=54; x_total=-217.00; y_total=16.00; x_step=-99. - frame misalignment: zoom_step=55; x_total=-217.00; y_total=16.00; x_step=-97. - frame misalignment: zoom_step=56; x_total=-217.00; y_total=16.00; x_step=-95. - frame misalignment: zoom_step=57; x_total=-217.00; y_total=16.00; x_step=-93. - frame misalignment: zoom_step=58; x_total=-217.00; y_total=16.00; x_step=-91. - frame misalignment: zoom_step=59; x_total=-217.00; y_total=16.00; x_step=-88. - frame misalignment: zoom_step=60; x_total=-217.00; y_total=16.00; x_step=-86. - frame misalignment: zoom_step=61; x_total=-217.00; y_total=16.00; x_step=-84. - frame misalignment: zoom_step=62; x_total=-217.00; y_total=16.00; x_step=-82. - frame misalignment: zoom_step=63; x_total=-217.00; y_total=16.00; x_step=-80. - frame misalignment: zoom_step=64; x_total=-217.00; y_total=16.00; x_step=-78. - frame misalignment: zoom_step=65; x_total=-217.00; y_total=16.00; x_step=-75. - frame misalignment: zoom_step=66; x_total=-217.00; y_total=16.00; x_step=-73. - frame misalignment: zoom_step=67; x_total=-217.00; y_total=16.00; x_step=-71. - frame misalignment: zoom_step=68; x_total=-217.00; y_total=16.00; x_step=-69. - frame misalignment: zoom_step=69; x_total=-217.00; y_total=16.00; x_step=-67. - frame misalignment: zoom_step=70; x_total=-217.00; y_total=16.00; x_step=-65. - frame misalignment: zoom_step=71; x_total=-217.00; y_total=16.00; x_step=-62. - frame misalignment: zoom_step=72; x_total=-217.00; y_total=16.00; x_step=-60. - frame misalignment: zoom_step=73; x_total=-217.00; y_total=16.00; x_step=-58. - frame misalignment: zoom_step=74; x_total=-217.00; y_total=16.00; x_step=-56. - frame misalignment: zoom_step=75; x_total=-217.00; y_total=16.00; x_step=-54. - frame misalignment: zoom_step=76; x_total=-217.00; y_total=16.00; x_step=-52. - frame misalignment: zoom_step=77; x_total=-217.00; y_total=16.00; x_step=-49. - frame misalignment: zoom_step=78; x_total=-217.00; y_total=16.00; x_step=-47. - frame misalignment: zoom_step=79; x_total=-217.00; y_total=16.00; x_step=-45. - frame misalignment: zoom_step=80; x_total=-217.00; y_total=16.00; x_step=-43. - frame misalignment: zoom_step=81; x_total=-217.00; y_total=16.00; x_step=-41.23; y_step=3.04
Error: could not broadcast input array from shape (576,1028,3) into shape (576,1025,3)
duncanthomson@Duncans-Mac-mini AI-Infinite-Zoom-Generator %

**Comment by beltoforion** [comment]
Thats not a crash. That is a hint that there is something wrong with your input images. Without getting the image sequence there is nothing i can do. Make sure all images have the same dimensions, make sure that the outpainting zoom factor is really what you submit. The fact that it fails on image 2 tells me something with your input is wrong.

Chances are you did not sort the images properly and you have auto sort turned off. Images must be sorted starting from the last one, NOT the first one. That is usually the reverse order of the animation because a zoom out is more suprising than a zoom in. The script will always compute a zoom in sequence that is why you must start with the last image.
