### ISSUE TITLE
get an "image misalignment error"

### ISSUE THREAD

**Issue by heaversm** [beltoforion/ai_ever_zoom#3]
Script runs, no errors are thrown, but get an image that opens with two images side by side with "Image Misalignnment Error" title.

<img width="768" alt="image" src="https://github.com/beltoforion/AI-Infinite-Zoom-Generator/assets/520541/869684a9-fb19-4cee-b58d-b0e8980be117">

Maybe you could provide a demo in the repo of the proper images.

**Comment by beltoforion** [comment]
You can find three sample sequences in this section of my web page:
https://beltoforion.de/en/infinite_zoom/index.php#idVideo

To me it looks like the images are not properly centered. The center of the right image is a different location than the center of the left image. The script can compensate small offsets it cannot compensate larger ones.

I can only give more specific feedback if i get the original image series.
