### ISSUE TITLE
Error: No enumerators available

### ISSUE THREAD

**Issue by sFinOe** [beltoforion/ai_ever_zoom#4]
hey im trying to run the script on google colab and i followed all the instructions but when i run the script 
`!python ./infinite_zoom.py -zf 2 -zs 100 -zc 0.8 -i ./sample_pirate -o video.mp4` 
i get error No enumerators available.

.
.
![Screenshot from 2024-01-27 19-09-01](https://github.com/beltoforion/AI-Infinite-Zoom-Generator/assets/93994921/37e4cc3d-84fe-4301-9b68-4452528ad7ac)

**Comment by beltoforion** [comment]
This script uses imshow from opencv which required an x server that is not available in a web browser
